-- Phase 4: vector search + hybrid semantic search.
-- Idempotent migration for Google text-embedding-004 (768 dimensions).

CREATE EXTENSION IF NOT EXISTS vector;

DROP INDEX IF EXISTS idx_embeddings_hnsw;

DO $$
DECLARE
    embedding_count BIGINT;
BEGIN
    SELECT COUNT(*) INTO embedding_count FROM spot_embeddings;

    -- Existing 384-dim rows cannot be cast to 768-dim vectors. They belong to
    -- the previous local MiniLM plan and are regenerated by Phase 4.
    IF embedding_count > 0 THEN
        DELETE FROM spot_embeddings
        WHERE model IS DISTINCT FROM 'text-embedding-004';
    END IF;
END $$;

ALTER TABLE spot_embeddings
    ALTER COLUMN embedding TYPE vector(768);

ALTER TABLE spot_embeddings
    ALTER COLUMN model SET DEFAULT 'text-embedding-004';

CREATE INDEX IF NOT EXISTS idx_embeddings_hnsw ON spot_embeddings
    USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_embeddings_model_created ON spot_embeddings(model, created_at DESC);
